apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: iotapps
spec:
  ports:
  - port: 1881
    protocol: TCP
    targetPort: 1881
    nodePort: 32000
  selector:
    app: ui
  type: NodePort