apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployer 
  namespace: iotapps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployer-clusterrole
  namespace: iotapps
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployer-rb
  namespace: iotapps
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deployer-clusterrole
subjects:
- kind: ServiceAccount
  name: deployer
  namespace: iotapps
---